name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1

      - name: Install dependencies
        run: |
          go mod download
      - name: Build and test Go application
        run: |
          go build -v ./...
          go test -v ./...

  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: sleya22/demo:${{ github.sha }}

      - name: Push Docker image
        run: docker push sleya22/demo:${{ github.sha }}

  trivy-docker:
    needs: build-and-push
    name: "Scan for docker vulnerabilities using Trivy"
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner for in docker mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "sleya22/demo:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          skip-dirs: "/go"
          vuln-type: "os,library"
          severity: "CRITICAL"

  trivy-repo:
    name: "Scan for code vulnerabilities using Trivy"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"


